### ISSUE TITLE
[Numpy] ValueError: need at least one array to stack

### ISSUE THREAD

**Issue by rjsheperd** [patrickmineault/vid2slides#1]
Hi, I made a fork of this repo and updated the `environment.yml` to get it running on my Macbook Air M1 laptop, but I am getting this error:

```
video:2959kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
vid2slides/vid2slides.py:258: RuntimeWarning: invalid value encountered in divide
  A = (1 - jump_probability) * np.eye(ncandidates) + jump_probability * T / T.sum(axis=1, keepdims=True)
vid2slides/vid2slides.py:265: RuntimeWarning: divide by zero encountered in log
  seq = log_viterbi(log_B, np.log(A), log_pi)
vid2slides/vid2slides.py:54: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  q = np.zeros(log_B.shape[0], dtype=np.int)
Traceback (most recent call last):
  File "vid2slides/vid2slides.py", line 441, in <module>
    extract_keyframes_from_video(args.in_path, args.out_path, args.tmp_path)
  File "vid2slides/vid2slides.py", line 411, in extract_keyframes_from_video
    info['crop'] = extract_crop(info)
  File "vid2slides/vid2slides.py", line 279, in extract_crop
    A = np.stack(ims, axis=0)
  File "<__array_function__ internals>", line 180, in stack
  File "/Users/rsheperd/opt/miniconda3/envs/vid2slides/lib/python3.8/site-packages/numpy/core/shape_base.py", line 422, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```

Running with miniconda. Here is my system info:
```
      Model Name: MacBook Air
      Model Identifier: MacBookAir10,1
      Model Number: MGN73LL/A
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 8 GB
      System Firmware Version: 8419.80.7
      OS Loader Version: 8419.80.7
```

**Comment by felciano** [comment]
I'm running into this too. @rjsheperd did you figure it out?

**Comment by rjsheperd** [comment]
@felciano Check out my fork here: https://github.com/rjsheperd/vid2slides
